#!/bin/bash

sudo apt install jq bat curl zsh git htop nmap tmux vim 

# Install dependencies for VIM
sudo apt install libxt-dev libx11-dev libxpm-dev python-dev python3-dev libncurses-dev

# Install dependencies for TMUX
sudo apt install -y automake bison pkg-config libevent-dev libncurses5-dev

[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"