let g:vim_home = get(g:, 'vim_home', expand('~/.vim/'))

" Load all vim configs {{{1
let config_list = [
      \ 'config.vim',
      \ 'commands.vim',
      \ 'material.vim',
      \ 'airline.vim',
      \ 'plugin.vim'
      \]
for files in config_list
  for f in glob(g:vim_home.files, 1, 1)
    exec 'source' f
  endfor
endfor

" Set at the end to work around 'exrc'
set secure
