### mpv configuration file ###

### Profile ###

include="~~/profiles.conf"

### Hardware Acceleration ###
hwdec=nvdec
vo=gpu
gpu-api=vulkan
hwdec-codecs=av1

### General Options ###
# Performance settings
video-sync=display-resample
save-position-on-quit=yes

### Audio and Subtitles ###

# slang=en,eng,English,ru,rus,Russian
# alang=ja,jp,jpn,jap,Japanese,en,eng,English,ru,rus,Russian

# sub-blur=0.5
# sub-scale=0.7
# sub-margin-y=60
# sub-color='#d6ffffff'
# sub-shadow-offset=5.0
# sub-font=Clear Sans Bold
# sub-back-color='#00000000'
# sub-border-color='#266a678c'
# sub-shadow-color='#00000000'

# sub-auto=all
# volume-max=150
# sub-fix-timing=yes
# audio-channels=auto  
# blend-subtitles=yes
# sub-ass-override=yes  
# audio-file-auto=fuzzy 
# audio-pitch-correction=yes
# audio-normalize-downmix=yes              
# sub-file-paths-append=subtitles
# demuxer-mkv-subtitle-preroll=yes
# sub-file-paths=sub;subs;subtitles
# af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'

### OSD/OSC ###

osc=no
border=no
osd-bar=no
osd-bold=no
osd-font-size=24
osd-font='JetBrains Mono'