# Set terminal settings
set -g default-terminal "screen-256color"

# Basic configurations
set -g prefix C-a  # Prefix key Ctrl-A
set -g set-titles on  # Enable terminal title setting
set-option -g set-titles-string '#h ❐ #S ● #I #W'  # Terminal title format

# Mouse settings
set -g mouse on  # Enable mouse scroll

# Timing settings
set -sg escape-time 1  # Escape time

# Pane indexing
set -g base-index 1
setw -g pane-base-index 1

# Sort sessions by name
bind s choose-tree -sZ -O name

# Rebind keys for convenience
unbind %
bind '|' split-window -h 
unbind '"'
bind \\ split-window -v
unbind r
bind R source-file ~/.tmux.conf
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind-key x kill-pane

# Set mode keys to vi
set-window-option -g mode-keys vi

# Key bindings for copy-mode-vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'  # TPM plugin manager
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'wfxr/tmux-power'

# Plugin settings
set -g @tmux_power_theme '#5FAFFF'
set -g @tmux_power_date_format '%F'
set -g @tmux_power_time_format '%T'
set -g @prefix_highlight_empty_has_affixes 'on'
set -g @prefix_highlight_empty_prompt ''
set -g @prefix_highlight_prefix_prompt ''
set -g @prefix_highlight_copy_prompt ''
set -g @prefix_highlight_sync_prompt ''
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
