export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export EDITOR='vim'
export VISUAL='vim'

# Optimize ZSH
if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

stty -ixon

# Setup Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dbox"
plugins=(git colorize zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Setup history
. ~/.dotfiles/zsh/compinit

# Setup history
. ~/.dotfiles/zsh/hist

# Setup zsh styles
. ~/.dotfiles/zsh/zstyles

# Setup Prompt
# . ~/.dotfiles/zsh/prompt

# Setup CDPATH for directory completion
. ~/.dotfiles/zsh/cdpath

# Setup functions
. ~/.dotfiles/zsh/funcs

# Setup aliases
. ~/.dotfiles/zsh/aliases


if [[ "$ZPROF" = true ]]; then
  zprof
fi

