# Environment Variables
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export EDITOR='vim'
export VISUAL='vim'
export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh

# Optimize ZSH
if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
  zprof
fi

stty -ixon

# Setup Oh My Zsh
ZSH_THEME="dbox"
plugins=(git colorize)
source $ZSH/oh-my-zsh.sh

# Source Plugins
source $DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Setup history, zsh styles, and aliases
. $DOTFILES/zsh/hist
. $DOTFILES/zsh/zstyles
. $DOTFILES/zsh/aliases
